# Generated by Django 3.2.4 on 2021-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='achievements',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
