# Generated by Django 3.2.4 on 2021-06-13 17:52

from django.db import migrations

from config.update_db_using_configs import add_test_user


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_test_user)
    ]
